// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters, constant_identifier_names

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> _ar = {
  "startJourney": "ابدأ رحلتك لتأمين صحة أطفالك وتذكيرك بأهم التطعيمات في مواعيدها.",
  "sideEffectsInfo": "تعرفي على الآثار الجانبية وكيفية التعامل معها، مع نصائح مباشرة من المتخصصين.",
  "safeMedicines": "اطلعي على أدوية آمنة لتخفيف الآثار الجانبية بعد التطعيم",
  "readyToStart": "جاهزة للبدء!",
  "explanatoryTextDescr": "يرجى التأكد من إحضار السجل الصحي للطفل عند الذهاب للتطعيم.",
  "yearAndFourMonth": "عام وأربع أشهر",
  "textTest1": "يرجى مراجعة الحالة الصحية للطفل قبل موعد التطعيم",
  "textTest2": "إذا كان ابنك يعاني من أي أمراض، يرجى استشارة الطبيب حول إمكانية تأجيل التطعيم.",
  "timeLineDetails": "الجرعة الأولى: عند عمر 6 أسابيع.\nالجرعة الثانية: عند عمر 10 أسابيع.\n(جرعة ثالثة إن وُجدت): عند عمر 14 أسبوعًا.",
  "intermittentSideEffects": "الأعراض الجانبية النادرة",
  "editPhoto": "تعديل صورة طفلك",
  "createNewAccount": "إنشاء حساب جديد",
  "name": "الإسم",
  "enterYourName": "قم بإدخال اسمك",
  "phoneNumber": "رقم الهاتف",
  "enterPhoneNumber": "أدخل رقم الهاتف",
  "emailAddress": "البريد الالكتروني",
  "enterEmailAddress": "أدخل بريدك الإلكتروني",
  "password": "كلمة المرور",
  "subtitleNotification": "هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها",
  "enterPassword": "أدخل كلمة المرور",
  "confirmPassword": "تأكيد كلمة المرور",
  "createAccount": "انشاء حساب",
  "continueText": "تخطي",
  "orRegisterUsing": "أو سجل بإستخدام",
  "alreadyHaveAccount": "هل لديك حساب بالفعل؟",
  "login": "تسجيل دخول",
  "forgotPassword": "هل نسيت كلمة المرور؟",
  "noAccountYet": "ليس لديك حساب؟",
  "resendCode": "إعادة الإرسال",
  "next": "التالي",
  "passwordResetCode": "كود تأكيد كلمه المرور",
  "changePassword": "تغيير كلمه المرور",
  "passwordChanged": "تم تغيير كلمه المرور",
  "welcomeMessage": "أهلاً بك كل ما تحتاجينه لصحة طفلك \n في مكان واحد",
  "addChildPhoto": "أضف صورة طفلك",
  "registerChildData": "هيا لنسجل بيانات طفلك!",
  "birthDate": "تاريخ الميلاد",
  "enterBirthDate": "قم بإدخال تاريخ ميلاد طفلك",
  "enterChildName": "قم بإدخال اسم طفلك",
  "height": "الطول",
  "weight": "الوزن",
  "gender": "النوع",
  "childDiseases": "هل يعانى طفلك من اى امراض ",
  "childVaccines": "هل اخذ طفلك اى تطعيمات من قبل",
  "register": "تسجيل",
  "geminiAnswerPrompt": "احصل علي إجابة سؤالك مع Gemini....",
  "welcomeLily": "مرحبا ليلي!",
  "nearbyPharmacies": "اماكن الصيدليات والوحدات القريبه",
  "vaccinationTimeRemaining": "الوقت المتبقي للتطعيم القادم",
  "articlesSideEffects": "مقالات عن الاعراض الجانبيه",
  "tipsBeforeAfterVaccination": "نصايح قبل وبعد التطعيم",
  "generalArticlesVaccinations": "مقالات عامه عن التطعيمات",
  "medicationDatabase": "قاعده بيانات عن الادويه",
  "favoriteItems": "العناصر المفضله",
  "articles": "مقالات",
  "doctors": "اطباء",
  "sideEffectsTuberculosisVaccine": "الاعراض الجانبيه لتطعيم الدرن",
  "effective99Percent": "فعال بنسبة99%",
  "singleDose": "يتم اخده مره واحده",
  "knowMore": "معرفه المزيد.....",
  "pediatricSpecialist": "اخصائيه اطفال ",
  "doctorName": "د/ مريم ناصر ",
  "rating": "4.2",
  "savedItems": "العناصر المحفوظه",
  "tuberculosis": "الدرن",
  "search": "بحث",
  "searchPlaceholder": "what do you want to search about",
  "basic": "اساسيه",
  "additional": "إضافية",
  "rotavirusVaccine": "تطعيم روتاتيك",
  "preVaccineTips": "1. تأكد من استشارة الطبيب: إذا كان الطفل يعاني من الحمى أو أي مرض، استشر الطبيب لتحديد ما إذا كان من المناسب تأجيل التطعيم. 2. جهّز السجل الطبي: احضر سجل التطعيمات السابق لتحديثه وضمان عدم عرض المزيد.....",
  "beforeVaccination": "قبل التطعيم",
  "postVaccination": "بعد التطعيم",
  "postVaccineTips": "1. راقب الآثار الجانبية: تحقق من وجود أي أعراض مثل احمرار أو تورم في مكان الحقن، حمى خفيفة، أو بكاء مستمر.\n2. استخدم الكمادات الباردة: ضع كمادات باردة على موضع الحقن لتخفيف عرض المزيد....",
  "sideEffects": "الاعراض الجانبيه",
  "notHaveCode": "لم تحصل على كود؟ ",
  "commonSideEffects": "الأعراض الجانبية الشائعة",
  "commonSideEffectsDetails": "1. احمرار أو تورم في موضع الحقن: يحدث غالبًا ويختفي خلال يوم أو يومين. 2. ألم خفيف في موضع الحقن: قد يشعر الطفل بألم عند قراءه المزيد......",
  "rareSideEffects": "1. طفح جلدي: يظهر أحيانًا بعد التطعيمات الفيروسية الحية (مثل الحصبة). 2. تورم الغدد الليمفاوية: قد يحدث بشكل طفيف ويزول بعد قراءه المزيد......",
  "handlingSideEffects": "كيفية التعامل مع الأعراض الجانبية",
  "commonSymptoms": "الأعراض الشائعة:",
  "generalArticles": "مقالات عامه عن التطعيمات",
  "aboutVaccine": "عن التطعيم",
  "vaccineDetails": "تفاصيل عن التطعيم",
  "loremIpsumExample1": "هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. ولذلك يتم استخدام طريقة لوريم إيبسوم لأنها تعطي توزيعاَ طبيعياَ -إلى حد ما- للأحرف عوضاً عن استخدام \"هنا يوجد محتوى نصي، هنا يوجد محتوى نصي\" فتجعلها تبدو (أي الأحرف) وكأنها نص مقروء. العديد من برامح النشر المكتبي وبرامح تحرير صفحات الويب تستخدم لوريم إيبسوم بشكل إفتراضي كنموذج عن النص، وإذا قراءه المزيد.....",
  "importanceOfVaccination": "أهمية هذا التطعيم",
  "loremIpsumExample2": "هنالك العديد من الأنواع المتوفرة لنصوص لوريم إيبسوم، ولكن الغالبية تم تعديلها بشكل ما عبر إدخال بعض النوادر أو الكلمات العشوائية إلى النص. إن كنت تريد أن تستخدم نص لوريم إيبسوم ما، عليك أن تتحقق أولاً أن ليس هناك أي كلمات أو عبارات محرجة أو غير لائقة مخبأة في هذا النص. بينما تعمل جميع مولّدات نصوص لوريم قراءه المزيد.....",
  "recommendedMedications": "الأدوية الموصى بها",
  "healthNote": "ملحوظة توعوية",
  "healthNoteDetails": "هذه المعلومات للاسترشاد فقط وليست بديلاً عن استشارة الطبيب. يرجى التأكد من استخدام الأدوية تحت إشراف طبي",
  "doctorInfo": "معلومات عن الطبيب",
  "sideEffectDetails": "إسهال خفيف، تقيؤ، حمى بسيطة، أو ألم بالبطن.ب",
  "doctorDetails": "عن هذا الطبيب",
  "doctorDescription": "الدكتور محمد هو طبيب أطفال متخصص في رعاية الأطفال منذ الولادة وحتى سن المراهقة. يتميز بخبرته الواسعة في متابعة نمو الأطفال وتطورهم، وتشخيص الأمراض الشائعة وعلاجها، مثل نزلات البرد، الحساسية، والالتهابات. كما يهتم بتقديم النصائح للأمهات حول التطعيمات اللازمة والتغذية السليمة للأطفال. الدكتور محمد معروف بتعامله الودود مع الأطفال وحرصه على تقديم أفضل رعاية طبية لهم.",
  "workHours": "مواعيد العمل",
  "workSchedule": "السبت - الأربعاء, ٨ صباحا :٢ ظهرا",
  "doctorReviews": "آراء عن هذا الطبيب",
  "patientReview": "الدكتور محمد شخص محترف وذو خبرة كبيرة في مجاله، يتميز بأسلوبه الواضح والبسيط في الشرح. يحرص دائمًا على تقديم المساعدة للمرضى بكل اهتمام وإخلاص.",
  "reviewerName": "هويدا النبوي",
  "writeComment": "اكتب تعليق.........",
  "doseCount": "عدد الجرعات",
  "timeline": "الجدول الزمني:",
  "sideEffectsLabel": "الآثار الجانبية:",
  "medicationsForSideEffects": "أدوية للتخفيف:",
  "medicationsForSideEffectsDetails": "للحُمّى: باراسيتامول (تحت إشراف الطبيب).\nللإسهال: محاليل الجفاف الفموية (ORS).\nللتقيؤ: تجنب الأطعمة الثقيلة مؤقتًا وتقديم السوائل تدريجيًا.",
  "medicationsDetails": "للحُمّى: باراسيتامول (تحت إشراف الطبيب). للإسهال: محاليل الجفاف الفموية (ORS). للتقيؤ: تجنب الأطعمة الثقيلة مؤقتًا وتقديم السوائل تدريجيًا.",
  "accountSettings": "اعدادات الحساب الشخصى",
  "themes": "الثيمات",
  "notifications": "الاشعارات",
  "language": "اللغه",
  "addChild": "اضافه طفل",
  "logout": "تسجيل خروج",
  "logoutConfirmation": "هل أنت متأكد أنك تريد تسجيل الخروج؟",
  "cancel": "إلغاء",
  "personalAccountSettings": "اعدادات الحساب الشخصي",
  "address": "العنوان",
  "profile": "الحساب الشخصي",
  "editAccount": "تعديل الحساب",
  "deleteAccount": "حذف الحساب",
  "change": "تغيير",
  "deleteAccountConfirmation": "هل أنت متأكد أنك تريد حذف حسابك؟",
  "delete": "حذف",
  "myChildren": "أطفالي",
  "age": "السن",
  "arabicLanguage": "اللغه العربيه",
  "englishLanguage": "اللغه الانجليزيه",
  "lightTheme": "فاتح",
  "darkTheme": "غامق",
  "noNotifications": "ليس لديك اشعارات فى الوقت الحال تعالى لاحقا",
  "noArticlesAvailable": "لا توجد مقالات متاحة حاليًا. تحقق لاحقًا للحصول على المزيد من المحتوى",
  "noFavoriteArticles": "قائمة المقالات المفضلين فارغة. أضف مقالات هنا لتظهر لاحقًا.",
  "noFavoriteDoctors": "قائمة الطباء المفضلين فارغة. أضف اطباء هنا لتظهر لاحقًا.",
  "notificationsLabel": "الإشعارات",
  "markAsRead": "تحديد كمقروءة",
  "today": "اليوم",
  "tuberculosisVaccineAppointment": "موعد تطعيم الدرن",
  "deleteAllNotifications": "حذف جميع الإشعارات",
  "deleteAllNotificationsConfirmation": "هل أنت متأكد أنك تريد حذف جميع الإشعارات؟",
  "vaccinationReminder": "لدى طفلك حمزة موعد تطعيم",
  "childName": "محمد عمرو",
  "vaccineNameLabel": "اسم التطعيم : ",
  "vaccinationPlaceLabel": "مكان التطعيم   : ",
  "vaccinationDateLabel": "تاريخ التطعيم   : ",
  "explanatoryText": "نص توضيحي : ",
  "informativeNote": "معلومه توضيحيه : ",
  "advice": "نصيحة: ",
  "postpone": "تأجيل",
  "confirm": "تأكيد",
  "enterPostponementDate": "يرجى ادخال الموعد بعد التاجيل",
  "postponementDate": "تاريخ التاجيل",
  "enterVaccinationDate": "قم بإدخال تاريخ التطعيم",
  "text": "تم تسجيل الدخول بنجاح",
  "firstName": "الاسم الاول",
  "LastName": "الاسم الثانى",
  "notSelectImage": "لم يتم اختيار صوره",
  "loginSuccess": "Login Successful",
  "unAvailable": "غير متاح",
  "name_required": "الاسم مطلوب",
  "name_invalid": "الاسم يجب أن يحتوي على حروف عربية أو إنجليزية فقط",
  "email_required": "البريد الإلكتروني مطلوب",
  "email_invalid": "الرجاء إدخال بريد إلكتروني صحيح",
  "password_required": "كلمة المرور مطلوبة",
  "password_length": "كلمة المرور يجب أن تكون 8 أحرف على الأقل",
  "password_invalid": "كلمة المرور يجب أن تحتوي على حرف واحد (عربي أو إنجليزي) ورقم واحد على الأقل",
  "confirm_password_required": "تأكيد كلمة المرور مطلوب",
  "confirm_password_mismatch": "كلمة المرور وتأكيد كلمة المرور غير متطابقتين",
  "phone_number_required": "رقم الهاتف مطلوب",
  "phone_number_invalid": "الرجاء إدخال رقم هاتف صحيح",
  "female1": "ذكر",
  "male1": "انثى",
  "welcome_message": "مرحباً بك في المساعد الطبي للأطفال\nيمكنك طرح أسئلتك هنا",
  "typing_indicator": "جاري الكتابة",
  "reset_chat_button": "إعادة المحادثة",
  "text_field_hint": "اكتب سؤالك هنا...",
  "appbar_title": "المساعد الطبي للأطفال"
};
static const Map<String,dynamic> _en = {
  "startJourney": "Start your journey to secure your children's health and remind you of the most important vaccinations on time.",
  "sideEffectsInfo": "Learn about side effects and how to deal with them, with direct advice from specialists.",
  "safeMedicines": "Discover safe medications to alleviate side effects after vaccination.",
  "readyToStart": "Ready to start!",
  "explanatoryTextDescr": "Please ensure to bring the child's health record when going for vaccination.",
  "yearAndFourMonth": "One year and four months",
  "textTest1": "Please review the child's health status before the vaccination appointment.",
  "textTest2": "If your child suffers from any illnesses, please consult a doctor about the possibility of postponing the vaccination.",
  "timeLineDetails": "First dose: At 6 weeks of age.\nSecond dose: At 10 weeks of age.\n(Third dose, if applicable): At 14 weeks of age.",
  "intermittentSideEffects": "Rare side effects",
  "editPhoto": "Edit your child's photo",
  "createNewAccount": "Create a new account",
  "name": "Name",
  "enterYourName": "Enter your name",
  "phoneNumber": "Phone number",
  "enterPhoneNumber": "Enter phone number",
  "emailAddress": "Email address",
  "enterEmailAddress": "Enter your email address",
  "password": "Password",
  "subtitleNotification": "It is a long-established fact that a page's readable content will distract the reader from focusing on the external appearance of the text or the layout of paragraphs on the page being read.",
  "enterPassword": "Enter password",
  "confirmPassword": "Confirm password",
  "createAccount": "Create account",
  "continueText": "Skip",
  "orRegisterUsing": "Or register using",
  "alreadyHaveAccount": "Already have an account?",
  "login": "Login",
  "forgotPassword": "Forgot your password?",
  "noAccountYet": "Don't have an account yet?",
  "resendCode": "Resend code",
  "next": "Next",
  "passwordResetCode": "Password reset code",
  "changePassword": "Change password",
  "passwordChanged": "Password changed",
  "welcomeMessage": "Welcome, everything you need for your child's health \n in one place",
  "addChildPhoto": "Add your child's photo",
  "registerChildData": "Let's register your child's information!",
  "birthDate": "Birth date",
  "enterBirthDate": "Enter your child's birth date",
  "enterChildName": "Enter your child's name",
  "height": "Height",
  "weight": "Weight",
  "gender": "Gender",
  "childDiseases": "Does your child suffer from any diseases?",
  "childVaccines": "Has your child received any previous vaccinations?",
  "register": "Register",
  "geminiAnswerPrompt": "Get your question answered with Gemini...",
  "welcomeLily": "Hello Lily!",
  "nearbyPharmacies": "Locations of nearby pharmacies and clinics",
  "vaccinationTimeRemaining": "Time remaining for the next vaccination",
  "articlesSideEffects": "Articles about side effects",
  "tipsBeforeAfterVaccination": "Tips before and after vaccination",
  "generalArticlesVaccinations": "General articles about vaccinations",
  "medicationDatabase": "Medication database",
  "favoriteItems": "Favorite items",
  "articles": "Articles",
  "doctors": "Doctors",
  "sideEffectsTuberculosisVaccine": "Side effects of the tuberculosis vaccine",
  "effective99Percent": "99% effective",
  "singleDose": "Taken once",
  "knowMore": "Learn more...",
  "pediatricSpecialist": "Pediatric specialist",
  "doctorName": "Dr. Maryam Nasser",
  "rating": "4.2",
  "savedItems": "Saved items",
  "tuberculosis": "Tuberculosis",
  "search": "Search",
  "searchPlaceholder": "What do you want to search about",
  "basic": "Basic",
  "additional": "Additional",
  "rotavirusVaccine": "Rotavirus vaccine",
  "preVaccineTips": "1. Consult a doctor: If the child has a fever or any illness, consult a doctor to determine if the vaccination should be postponed. 2. Prepare the medical record: Bring the previous vaccination record to update it and ensure no more is shown...",
  "beforeVaccination": "Before vaccination",
  "postVaccination": "After vaccination",
  "postVaccineTips": "1. Monitor side effects: Check for symptoms such as redness or swelling at the injection site, mild fever, or persistent crying.\n2. Use cold compresses: Apply cold compresses to the injection site to alleviate more...",
  "sideEffects": "Side effects",
  "notHaveCode": "Didn't receive a code?",
  "commonSideEffects": "Common side effects",
  "commonSideEffectsDetails": "1. Redness or swelling at the injection site: Often occurs and resolves within a day or two. 2. Mild pain at the injection site: The child may feel pain when reading more...",
  "rareSideEffects": "1. Rash: Sometimes appears after live viral vaccines (e.g., measles). 2. Swollen lymph nodes: May occur mildly and resolve after reading more...",
  "handlingSideEffects": "How to handle side effects",
  "commonSymptoms": "Common symptoms:",
  "generalArticles": "General articles about vaccinations",
  "aboutVaccine": "About the vaccine",
  "vaccineDetails": "Vaccine details",
  "loremIpsumExample1": "It is a long-established fact that a page's readable content will distract the reader from focusing on the external appearance of the text or the layout of paragraphs on the page being read. Therefore, Lorem Ipsum is used because it provides a somewhat natural distribution of letters, as opposed to using 'here is text content, here is text content,' making it appear as readable text. Many desktop publishing programs and web editing software use Lorem Ipsum as a default text model, and if you read more...",
  "importanceOfVaccination": "Importance of this vaccination",
  "loremIpsumExample2": "There are many variations of Lorem Ipsum texts available, but most have been altered in some way by adding humorous or random words to the text. If you want to use a Lorem Ipsum text, you should first ensure that there are no embarrassing or inappropriate words or phrases hidden in the text. While all Lorem Ipsum text generators read more...",
  "recommendedMedications": "Recommended medications",
  "healthNote": "Awareness note",
  "healthNoteDetails": "This information is for guidance only and is not a substitute for consulting a doctor. Please ensure medications are used under medical supervision.",
  "doctorInfo": "Doctor information",
  "sideEffectDetails": "Mild diarrhea, vomiting, mild fever, or abdominal pain.",
  "doctorDetails": "About this doctor",
  "doctorDescription": "Dr. Mohammed is a pediatrician specialized in caring for children from birth to adolescence. He is distinguished by his extensive experience in monitoring children's growth and development, diagnosing and treating common illnesses such as colds, allergies, and infections. He also focuses on providing advice to mothers about necessary vaccinations and proper nutrition for children. Dr. Mohammed is known for his friendly approach with children and his commitment to providing the best medical care for them.",
  "workHours": "Work hours",
  "workSchedule": "Saturday - Wednesday, 8 AM - 2 PM",
  "doctorReviews": "Reviews about this doctor",
  "patientReview": "Dr. Mohammed is a professional with vast experience in his field, distinguished by his clear and simple explanation style. He always strives to provide assistance to patients with care and dedication.",
  "reviewerName": "Huda Al-Nabawi",
  "writeComment": "Write a comment...",
  "doseCount": "Number of doses",
  "timeline": "Timeline:",
  "sideEffectsLabel": "Side effects:",
  "medicationsForSideEffects": "Medications for relief:",
  "medicationsForSideEffectsDetails": "For fever: Paracetamol (under medical supervision).\nFor diarrhea: Oral rehydration solutions (ORS).\nFor vomiting: Avoid heavy foods temporarily and offer fluids gradually.",
  "medicationsDetails": "For fever: Paracetamol (under medical supervision). For diarrhea: Oral rehydration solutions (ORS). For vomiting: Avoid heavy foods temporarily and offer fluids gradually.",
  "accountSettings": "Personal account settings",
  "themes": "Themes",
  "notifications": "Notifications",
  "language": "Language",
  "addChild": "Add child",
  "logout": "Logout",
  "logoutConfirmation": "Are you sure you want to log out?",
  "cancel": "Cancel",
  "personalAccountSettings": "Personal account settings",
  "address": "Address",
  "profile": "Profile",
  "editAccount": "Edit account",
  "deleteAccount": "Delete account",
  "change": "Change",
  "deleteAccountConfirmation": "Are you sure you want to delete your account?",
  "delete": "Delete",
  "myChildren": "My children",
  "age": "Age",
  "arabicLanguage": "Arabic language",
  "englishLanguage": "English language",
  "lightTheme": "Light",
  "darkTheme": "Dark",
  "noNotifications": "You have no notifications at the moment, come back later.",
  "noArticlesAvailable": "No articles are available at the moment. Check back later for more content.",
  "noFavoriteArticles": "The favorite articles list is empty. Add articles here to appear later.",
  "noFavoriteDoctors": "The favorite doctors list is empty. Add doctors here to appear later.",
  "notificationsLabel": "Notifications",
  "markAsRead": "Mark as read",
  "today": "Today",
  "tuberculosisVaccineAppointment": "Tuberculosis vaccine appointment",
  "deleteAllNotifications": "Delete all notifications",
  "deleteAllNotificationsConfirmation": "Are you sure you want to delete all notifications?",
  "vaccinationReminder": "Your child Hamza has a vaccination appointment",
  "childName": "Mohammed Amr",
  "vaccineNameLabel": "Vaccine name: ",
  "vaccinationPlaceLabel": "Vaccination place: ",
  "vaccinationDateLabel": "Vaccination date: ",
  "explanatoryText": "Explanatory text: ",
  "informativeNote": "Informative note: ",
  "advice": "Advice: ",
  "postpone": "Postpone",
  "confirm": "Confirm",
  "enterPostponementDate": "Please enter the rescheduled date",
  "postponementDate": "Postponement date",
  "enterVaccinationDate": "Enter the vaccination date",
  "text": "Login successful",
  "firstName": "First name",
  "LastName": "Last name",
  "notSelectImage": "No image selected",
  "loginSuccess": "Login Successful",
  "unAvailable": "Unavailable",
  "name_required": "Name is required",
  "name_invalid": "Name must contain only Arabic or English letters",
  "email_required": "Email is required",
  "email_invalid": "Please enter a valid email",
  "password_required": "Password is required",
  "password_length": "Password must be at least 8 characters long",
  "password_invalid": "Password must contain at least one letter (Arabic or English) and one number",
  "confirm_password_required": "Password confirmation is required",
  "confirm_password_mismatch": "Password and confirm password do not match",
  "phone_number_required": "Phone number is required",
  "phone_number_invalid": "Please enter a valid phone number",
  "female1": "Female",
  "male1": "Male",
  "typing_indicator": "Typing...",
  "reset_chat_button": "Restart Chat",
  "text_field_hint": "Type your question here...",
  "appbar_title": "Children's Medical Assistant"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"ar": _ar, "en": _en};
}
